### ISSUE TITLE
Quartz Tools & Sword Crashes Game in Anvil

### ISSUE THREAD

**Issue by FuhDis** [Draylar/vanilla-toolsets#10]
Version 1.14.2

Quartz sword, pickaxe, shovel, & hoe crashes the game when combining in the
 anvil.
Quartz armor works just fine & so does the equipment from every other added set.

[New Paste 1.txt](https://github.com/Draylar/vanilla-toolsets/files/3305753/New.Paste.1.txt)

ToolMaterialQuartz appears to be returning null on getRepairIngredient()

**Comment by Draylar** [comment]
Thanks for the report; fixed in 1.1.3.
