### ISSUE TITLE
About translation issues

### ISSUE THREAD

**Issue by lvck1** [Draylar/vanilla-toolsets#4]
[zh_cn.txt](https://github.com/Draylar/vanilla-toolsets/files/3176738/zh_cn.txt)
I am a Chinese player.I like this mod,but I found that the mod do not have a zh_cn language.So I made it for myself.I hope you can add it to the mod in the next update.
The github can't upload .json file,I convert it to .txt.
Thank you. o(*￣▽￣*)ブ

**Comment by Draylar** [comment]
Sorry for the late response! This will be added in 1.1.2. Thanks for the help.
